# Generated by Django 6.0.6 on 2026-06-05 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancereview',
            old_name='goals',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='period_start',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='rating',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='attendance_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='communication_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='productivity_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='teamwork_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='technical_skills_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'Leave'), ('HALF_DAY', 'Half Day')], default='PRESENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('EARNED', 'Earned Leave')], default='CASUAL', max_length=20),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
